name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 🧪 שלב 1: Checkout קוד
    - name: Checkout code
      uses: actions/checkout@v3

    # ⚙️ שלב 2: התקנת תלויות והרצת האפליקציה
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run app in background
      run: nohup python app.py &

    # ✅ שלב 3: בדיקות יחידה
    - name: Test app response
      run: curl http://localhost:5000

    # 📦 שלב 4: בניית Docker Image
    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/entrytracker:latest .

    # 🔄 שלב 5: בדיקות End-to-End עם Docker Compose
    - name: Run docker-compose
      run: docker-compose up -d

    - name: Run E2E test
      run: curl http://localhost:5000

    # ☁️ שלב 6: התחברות ל-Docker Hub ודחיפת ה-image
    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Push image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/entrytracker:latest

